sudo: true
language: c
before_install:
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/bin/*
  - export PATH=${TRAVIS_BUILD_DIR}/buildroot/bin/:${PATH}
install:
  # Remove unwanted warnings
  - sudo apt-get update
  - sudo apt-get install -y libc6-i386
  # Install arduino 1.8.5
  - wget http://downloads-02.arduino.cc/arduino-1.8.5-linux64.tar.xz
  - tar xf arduino-1.8.5-linux64.tar.xz
  - mv arduino-1.8.5 $HOME/arduino
  - ln -s $HOME/arduino ${TRAVIS_BUILD_DIR}/buildroot/bin/arduino

  - git clone https://github.com/bblanchon/ArduinoJson $HOME/Arduino/libraries/ArduinoJson
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - arduino --install-boards "esp8266:esp8266"
  # Install external libraries
  - install_dependencies
before_script:
  - cd ${TRAVIS_BUILD_DIR}
script:
  - build_weather-station
