language: c
sudo: false
before_install:
  - export PATH=${TRAVIS_BUILD_DIR}/buildroot/bin/:${PATH}
  - source adafruit_travis_ci.sh
install:
  - install_dependencies
script:
  - build_platform esp8266
