sudo: true
language: c
before_install:
  # Publish the buildroot script folder
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/bin/*
  - export PATH=${TRAVIS_BUILD_DIR}/buildroot/bin/:${PATH}
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - install_dependencies
before_script:
  - cd ${TRAVIS_BUILD_DIR}
script:
  - build_weather-station
